# Horizontal Pod Autoscaling
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-deploy
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: resource-container
  minReplicas: 1
  maxReplicas: 20
  targetCPUUtilizationPercentage: 50 
  #A base sempre é o request 50% do Request limit
