apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-c
spec:
  selector:
    matchLabels:
      app: nginx-c
  template:
    metadata:
      labels:
        app: nginx-c
    spec:
      containers:
      - name: nginx-c
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - "nginx-b"
              topologyKey: kubernetes.io/hostname