apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-b
spec:
  selector:
    matchLabels:
      app: nginx-b
  template:
    metadata:
      labels:
        app: nginx-b
    spec:
      containers:
      - name: nginx-b
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            # cpu: "100m"
        ports:
        - containerPort: 80
