apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template: 
    metadata:       
      labels:
        app: api
    spec:      
      containers:
      - name: api
        image: fabricioveronez/pedelogo-catalogo:v1.0.0
        ports:
        - containerPort: 80
        imagePullPolicy: Always
        startupProbe:
          httpGet:
            path: /read
            port: 80
            scheme: HTTP
          failureThreshold: 30
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /read
            port: 80
            scheme: HTTP
        livenessProbe:
          httpGet:
            path: /health
            port: 80
            scheme: HTTP
          initialDelaySeconds: 50
          periodSeconds: 30
          # successThreshold: 3
          timeoutSeconds: 20
          failureThreshold: 3
        envFrom:
          - configMapRef:
              name: api-configmap
        env:
          - name: Mongo__User
            valueFrom:
              secretKeyRef:
                key: MONGO_INITDB_ROOT_USERNAME
                name: mongodb-secret
          - name: Mongo__Password
            valueFrom:
              secretKeyRef:
                key: MONGO_INITDB_ROOT_PASSWORD
                name: mongodb-secret
