global:
route:
  receiver: Default
  group_by: ['alertname']
  group_wait: 15s
  group_interval: 15s
  repeat_interval: 5m

  routes:
    - receiver: MongoDBAlert
      match:
        team: mongodb

    - receiver: AlertaWebApi
      match:
        team: webapi

receivers:
- name: Default
  webhook_configs:
    - url: 'http://pruu.herokuapp.com/dump/wpwebhookdefault'
- name: MongoDBAlert
  webhook_configs:
    - url: 'http://pruu.herokuapp.com/dump/wpwebhookmongodb'
- name: AlertaWebApi
  webhook_configs:
    - url: 'http://pruu.herokuapp.com/dump/wpwebhookwebapi'
